name: Generate Dokka Docs and Commit to Docs Folder

on:
  push:
    branches:
      - develop

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Generate Dokka HTML Documentation
        run: ./gradlew dokkaHtml

      - name: Move Documentation to Docs Folder
        run: |
          mkdir -p docs
          rm -rf docs/*  # Clean previous docs
          cp -r app/build/dokka/html/* docs/

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.BOT_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Commit and Push Documentation
        run: |
          git add docs
          git commit -m "docs: Update Dokka documentation"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}